### ISSUE TITLE
Update license and cutoffDate year to 2018 (first-timers-only)

### ISSUE THREAD

**Issue by cg-cnu** [DAVFoundation/community#15]
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before and are looking for an easy way take their first steps.

Consider this as your chance to dip your toe into the world of open-source and get some bragging rights for writing code that makes drones fly, cars find charging stations, helps people and goods move from place to place and more...

Find more **first-timers-only** issues from DAV Foundation [here](https://github.com/search?q=org%3ADAVFoundation+is%3Aissue+is%3Aopen+label%3Afirst-timers-only).

Thank you for your help :heart:

## What is this project?

DAV (Decentralized Autonomous Vehicles) is a new non-profit foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### Community

The DAV project you are looking at is Community. Community is the backend server for the DAV's community site, which you can see at https://my.dav.network/

### The Issue
You need to update two dates...
- [ ] Update the copyright info in `LICENSE` file at the root of the project from `2017`  to `2018`

### Contributing to Community

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Open the [Community GitHub page](https://github.com/DAVFoundation/community) and click the ★ Star and then ⑂ Fork buttons.
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/community.git`
- [ ] **Make changes in the src/config/index.js and LICENSE files**
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/community](https://github.com/YOUR-USER-NAME/community)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#1`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

**Comment by ayamane** [comment]
I would like to work on this issue.  Seems like a good first-timer issue!

**Comment by cg-cnu** [comment]
Go ahead @ayamane it's yours :)

**Comment by TalAter** [comment]
@ayamane - Please only update the copyright, not the `cutoffDate`

**Comment by ayamane** [comment]
Great, thanks!  
I wasn't able to clone using the command provided above.  Error was:  Permission denied (publickey).  fatal:  Could not read from repository.  Please make sure you have the correct access rights.
I used GitHub Desktop application as a workaround.  Is this ok?

**Comment by ayamane** [comment]
@TalAter - ok, noted.

**Comment by cg-cnu** [comment]
Congratulations on your first opensource contribution @ayamane 🎆 👏 Hope this is the staring of many amazing contributions. Feel free to join our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors) to find out more opportunities to contribute to opensource 🙂

**Comment by ayamane** [comment]
@cg-cnu - great, thanks!  I'll take a look and hopefully can contribute something more meaningful.  My background is C#, SQL, javascript, Progress 4GL if there is anything specific you think might be a fit let me know!
